13
Exception in thread Thread-1 (sweep):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
13
    self._target(*self._args, **self._kwargs)
TypeError: sweep() takes 4 positional arguments but 5 were given
13
12
13
13
14
33
51
397
639
809
927
1011
1069
1109
1138
1158
1172
1182
1188
Exception in thread Thread-2 (sweep):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: sweep() takes 4 positional arguments but 5 were given
1193
864
633
471
358
612
790
914
1001
1062
1105
1135
1156
1170
1180
1188
Exception in thread Thread-3 (sweep):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: sweep() takes 4 positional arguments but 5 were given
1193
1196
1199
1200
1202
1202
1203
1203
1204
870
637
473
359
279
223
183
156
137
124
115
442
671
Exception in thread Thread-4 (sweep):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: sweep() takes 4 positional arguments but 5 were given
831
943
1021
1076
1115
1142
827
607
453
344
269
216
513
720
865
967
1038
1088
Exception in thread Thread-5 (sweep):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: sweep() takes 4 positional arguments but 5 were given
1123
1147
1165
1176
1185
1191
1195
1198
1200
1201
1202
1203
1203
1204
1204
Exception in thread Thread-6 (sweep):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: sweep() takes 4 positional arguments but 5 were given
1204
1204
1204
1204
872
638
475
361
281
225
519
392
635
473
360
280
224
186
158
139
125
116
109
105
102
99
98
97
96
95
95
95
Exception in thread Thread-7 (sweep):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: sweep() takes 4 positional arguments but 5 were given
95
95
95
94
94
94
94
94
94
94
94
94
94
94
94
94
94
94
94
94
94
94
427
660
823
938
1018
1074
1113
1140
1159
Exception in thread Thread-8 (sweep):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: sweep() takes 4 positional arguments but 5 were given
1173
1182
1189
1194
1197
1199
1201
1202
1202
1203
1203
1204
1204
1204
1204
Exception in thread Thread-9 (sweep):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: sweep() takes 4 positional arguments but 5 were given
1204
1204
1204
1204
1204
1204
1204
1204
1204
1204
1204
1204
1204
Exception in thread Thread-10 (sweep):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
TypeError: sweep() takes 4 positional arguments but 5 were given
1204
1204
1204
1204
1204
1204
1204
1204
>>> 